name: Contributor List
on:
  push:
    branches:
      - master
jobs:
  contributor_list:
    name: Contributor List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker://cjdenio/contributor_list:latest
        with:
          commit_message: 📝 Update contributors list
          # Max number of contributors to display on the README
          max_contributors: 10 # Default: 10
          # This enables showing contribution numbers on the README.
          # ⚠️ THIS WILL PUSH TO THE REPO AFTER EVERY COMMIT ⚠️
          show_numbers: false # Default: false